var nome = prompt('Digite seu nome')
var idade = prompt('Digite sua idade')
var emprego = prompt('Digite seu emprego atual')
var endereço = prompt('Digite seu endereço')
alert(`Seu nome é ${nome} \n Voce tem ${idade} anos \n seu emprego atual é: ${emprego} \n e mora no endereço ${endereço}`)